// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static String _env(String key) {
    final value = String.fromEnvironment(key, defaultValue: '');
    if (value.isEmpty) {
      throw StateError(
        'Missing Firebase config for $key. '
        'Pass it via --dart-define or --dart-define-from-file.',
      );
    }
    return value;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _webFromEnv();
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _androidFromEnv();
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return _windowsFromEnv();
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _webFromEnv() => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_WEB'),
    appId: _env('FIREBASE_APP_ID_WEB'),
    messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _env('FIREBASE_PROJECT_ID'),
    authDomain: _env('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _env('FIREBASE_STORAGE_BUCKET'),
    measurementId: _env('FIREBASE_MEASUREMENT_ID_WEB'),
  );

  static FirebaseOptions _androidFromEnv() => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_ANDROID'),
    appId: _env('FIREBASE_APP_ID_ANDROID'),
    messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _env('FIREBASE_PROJECT_ID'),
    storageBucket: _env('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions _windowsFromEnv() => FirebaseOptions(
    apiKey: _env('FIREBASE_API_KEY_WINDOWS'),
    appId: _env('FIREBASE_APP_ID_WINDOWS'),
    messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _env('FIREBASE_PROJECT_ID'),
    authDomain: _env('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _env('FIREBASE_STORAGE_BUCKET'),
    measurementId: _env('FIREBASE_MEASUREMENT_ID_WINDOWS'),
  );
}
