// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ⚠️  Firebase config is loaded from --dart-define at build/run time.
///
/// HOW TO RUN:
///   1. Create a `firebase_config.json` file (DO NOT COMMIT IT — add to .gitignore)
///   2. Run: flutter run --dart-define-from-file=firebase_config.json
///   3. Build: flutter build apk --dart-define-from-file=firebase_config.json
///
/// See .env.example for the required keys.
class DefaultFirebaseOptions {
  static const String _apiKeyWeb = String.fromEnvironment('FIREBASE_API_KEY_WEB');
  static const String _appIdWeb = String.fromEnvironment('FIREBASE_APP_ID_WEB');
  static const String _messagingSenderId = String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
  static const String _projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
  static const String _authDomain = String.fromEnvironment('FIREBASE_AUTH_DOMAIN');
  static const String _storageBucket = String.fromEnvironment('FIREBASE_STORAGE_BUCKET');
  static const String _measurementIdWeb = String.fromEnvironment('FIREBASE_MEASUREMENT_ID_WEB');
  static const String _apiKeyAndroid = String.fromEnvironment('FIREBASE_API_KEY_ANDROID');
  static const String _appIdAndroid = String.fromEnvironment('FIREBASE_APP_ID_ANDROID');
  static const String _apiKeyWindows = String.fromEnvironment('FIREBASE_API_KEY_WINDOWS');
  static const String _appIdWindows = String.fromEnvironment('FIREBASE_APP_ID_WINDOWS');
  static const String _measurementIdWindows = String.fromEnvironment('FIREBASE_MEASUREMENT_ID_WINDOWS');

  /// Returns true if all required keys for the given platform are present.
  static bool get isConfigured {
    if (kIsWeb) {
      return _apiKeyWeb.isNotEmpty &&
          _appIdWeb.isNotEmpty &&
          _projectId.isNotEmpty;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _apiKeyAndroid.isNotEmpty &&
            _appIdAndroid.isNotEmpty &&
            _projectId.isNotEmpty;
      case TargetPlatform.windows:
        return _apiKeyWindows.isNotEmpty &&
            _appIdWindows.isNotEmpty &&
            _projectId.isNotEmpty;
      default:
        return false;
    }
  }

  /// Returns null if config is missing instead of throwing.
  static FirebaseOptions? get currentPlatformOrNull {
    if (!isConfigured) return null;
    return currentPlatform;
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _webFromEnv();
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _androidFromEnv();
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS. '
          'Run the FlutterFire CLI again to add iOS support.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS. '
          'Run the FlutterFire CLI again to add macOS support.',
        );
      case TargetPlatform.windows:
        return _windowsFromEnv();
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _webFromEnv() => FirebaseOptions(
        apiKey: _apiKeyWeb,
        appId: _appIdWeb,
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        authDomain: _authDomain,
        storageBucket: _storageBucket,
        measurementId: _measurementIdWeb,
      );

  static FirebaseOptions _androidFromEnv() => FirebaseOptions(
        apiKey: _apiKeyAndroid,
        appId: _appIdAndroid,
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        storageBucket: _storageBucket,
      );

  static FirebaseOptions _windowsFromEnv() => FirebaseOptions(
        apiKey: _apiKeyWindows,
        appId: _appIdWindows,
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        authDomain: _authDomain,
        storageBucket: _storageBucket,
        measurementId: _measurementIdWindows,
      );
}
